name: torrent_bencode
description: >
  This library provides classes to encode/decode bencoded bytes, 
  implemented in pure dartlang.
version: 0.1.0+1
homepage: https://github.com/xtyxtyx/bencode
author: xuty <xty50337@hotmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
